updated OSMr5 with Eclipse fog05 connector
Signed-off-by: gabrik <gabriele.baldoni@gmail.com>

diff --git a/docker/Dockerfile-local b/docker/Dockerfile-local
--- a/docker/Dockerfile-local
+++ b/docker/Dockerfile-local
@@ -2,40 +2,39 @@ from ubuntu:xenial
 
 LABEL authors="Gennadiy Dubina, Alfonso Tierno, Gerardo Garcia"
 
-COPY . /root/RO
-
-COPY docker/scripts/ /bin/RO
-
 RUN apt-get update && \
     DEBIAN_FRONTEND=noninteractive apt-get -y install software-properties-common && \
-    DEBIAN_FRONTEND=noninteractive add-apt-repository -y cloud-archive:ocata && \
+    DEBIAN_FRONTEND=noninteractive add-apt-repository -y cloud-archive:queens && \
     apt-get update && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install git make python python-pip debhelper && \
+    DEBIAN_FRONTEND=noninteractive apt-get -y install git python python-pip && \
     DEBIAN_FRONTEND=noninteractive apt-get -y install wget tox && \
-    DEBIAN_FRONTEND=noninteractive pip install pip==9.0.3 && \
-    DEBIAN_FRONTEND=noninteractive pip install -U setuptools setuptools-version-command stdeb && \
-    DEBIAN_FRONTEND=noninteractive pip install -U pyang pyangbind && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install python-yaml python-netaddr python-boto && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install software-properties-common && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install python-novaclient python-keystoneclient python-glanceclient python-cinderclient python-neutronclient && \
-    DEBIAN_FRONTEND=noninteractive pip install -U progressbar pyvmomi pyvcloud==19.1.1 && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install python-argcomplete python-bottle python-cffi python-packaging python-paramiko python-pkgconfig libmysqlclient-dev libssl-dev libffi-dev python-mysqldb && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install python-logutils python-openstackclient python-openstacksdk && \
-    DEBIAN_FRONTEND=noninteractive pip install untangle && \
-    DEBIAN_FRONTEND=noninteractive pip install -e git+https://github.com/python-oca/python-oca#egg=oca && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install python-bitarray && \
-    DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-client && \
-    mkdir -p /root/RO && \
-    make -C /root/RO clean all BRANCH=master && \
-    dpkg -i /root/RO/IM/deb_dist/python-pyang_*.deb && \
-    dpkg -i /root/RO/IM/deb_dist/python-pyangbind_*.deb && \
-    dpkg -i /root/RO/IM/deb_dist/python-osm-im*.deb && \
-    dpkg -i /root/RO/openvim/.build/python-lib-osm-openvim*.deb && \
-    dpkg -i /root/RO/.build/python-osm-ro*.deb && \
+    DEBIAN_FRONTEND=noninteractive pip2 install pip==9.0.3 && \
+    DEBIAN_FRONTEND=noninteractive pip2 install -U progressbar pyvmomi pyvcloud==19.1.1 && \
+    DEBIAN_FRONTEND=noninteractive apt-get -y install python-novaclient python-keystoneclient python-glanceclient python-cinderclient python-neutronclient python-networking-l2gw && \
+    DEBIAN_FRONTEND=noninteractive apt-get -y install python-cffi libmysqlclient-dev libssl-dev libffi-dev python-mysqldb && \
+    DEBIAN_FRONTEND=noninteractive apt-get -y install python-openstacksdk python-openstackclient && \
+    DEBIAN_FRONTEND=noninteractive apt-get -y install python-networkx && \
+    DEBIAN_FRONTEND=noninteractive pip2 install untangle && \
+    DEBIAN_FRONTEND=noninteractive pip2 install -e git+https://github.com/python-oca/python-oca#egg=oca && \
+    DEBIAN_FRONTEND=noninteractive apt-get -y install mysql-client
+
+COPY . /root/RO
+
+RUN apt-get -y install python-requests && \
+    mkdir -p /root/fos && \
+    cd  /root/fos && \
+    git clone https://github.com/eclipse/fog05 && \
+    cd fog05/src/api/python/rest_api/ && \
+    python setup.py install && \
+    cd ~ && \
+    /root/RO/scripts/install-osm-im.sh --develop && \
+    /root/RO/scripts/install-lib-osm-openvim.sh --develop && \
+    make -C /root/RO prepare && \
+    mkdir -p /var/log/osm && \
+    pip2 install -e /root/RO/build && \
     rm -rf /root/.cache && \
     apt-get clean && \
-    rm -rf /var/lib/apt/lists/* && \
-    rm -rf /root/RO
+    rm -rf /var/lib/apt/lists/*
 
 VOLUME /var/log/osm
 
@@ -55,6 +54,7 @@ EXPOSE 9090
 # RO_DB_OVIM_PORT:        default value '3306'
 # RO_DB_NAME:             default value 'mano_db'
 # RO_DB_OVIM_NAME:        default value 'mano_vim_db'
+# RO_LOG_FILE:            default log to stderr if not defined
 
 ENV RO_DB_HOST="" \
     RO_DB_OVIM_HOST="" \
@@ -67,7 +67,11 @@ ENV RO_DB_HOST="" \
     RO_DB_PORT=3306 \
     RO_DB_OVIM_PORT=3306 \
     RO_DB_NAME=mano_db \
-    RO_DB_OVIM_NAME=mano_vim_db
+    RO_DB_OVIM_NAME=mano_vim_db \
+    OPENMANO_TENANT=osm \
+    RO_LOG_LEVEL=DEBUG
 
-CMD /bin/RO/start.sh
+CMD RO-start.sh
 
+# HEALTHCHECK --start-period=30s --interval=10s --timeout=5s --retries=12 \
+#  CMD curl --silent --fail localhost:9090/openmano/tenants || exit 1
